- name: Verify
  hosts: all
  become: true

  tasks:
  - name: Bare include (free-form)
    include_vars: ../../defaults/main.yml

  - name: Check that dokku_global_cert module can parse output
    dokku_global_cert:
      state: absent

  - name: Get dokku_hostname    # noqa 301
    command: dokku domains:report --global
    register: dokku_domains

  - name: Check that dokku_hostname is set correctly
    assert:
      that:
      - "'test.domain' in dokku_domains.stdout"
      msg: |
        hostname 'test.domain' not found in output of 'dokku domains':
        {{ dokku_domains.stdout }}

  # check apt sources configuration
  # Note: cannot use apt module for this https://stackoverflow.com/questions/51410696
  - name: Run apt update  # noqa 303 301
    command: apt-get update
    register: apt_update

  - name: Check that apt update output does not contain warnigns
    assert:
      that:
      - "'W:' not in apt_update.stderr"
      msg: |
        Found warnings in output of `apt update`:
        {{ apt_update.stderr }}

  - name: Create APP
    dokku_app:
      app: example-app

  - name: Get list of apps  # noqa 301
    command: dokku apps:list
    register: dokku_apps

  - name: Check that example_app is in list of apps
    assert:
      that:
      - "'example-app' in dokku_apps.stdout"
      msg: |
        'example_app' not found in output of 'dokku apps:list':
        {{ dokku_apps.stdout }}

  - name: Set resource limits for a example_app
    dokku_resource_limit:
      resources:
        cpu: 150
      app: example-app

  - name: Get lisf of a resources for a example_app
    command: dokku resource:limit example-app
    register: dokku_resource_limit

  - name: Check that example-app have resource limits
    assert:
      that:
      - "'cpu: 150' in dokku_resource_limit.stdout"
      msg: |
        Limits for a example app not found in output of 'dokku resource:limit example-app':
        {{ dokku_resource_limit.stdout }}
